### ISSUE TITLE
question . does it support arm device . for example . raspberry pi or odroid.

### ISSUE THREAD

**Issue by asakous** [drdteam/gzdoom-gles#1]
I got 
W_Init: Init WADfiles.
 adding /storage/gzdoom-lite/gzdoom.pk3, 682 lumps
 adding /storage/gzdoom-lite/game_support.pk3, 2514 lumps
 adding /storage/.config/gzdoom/doom2.wad, 2919 lumps
 adding /storage/gzdoom-lite/game_widescreen_gfx.pk3, 39 lumps
I_Init: Setting up machine state.
V_Init: allocate screen.
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device ALSA Default
  EFX enabled
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
script parsing took 1397.14 ms
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading custom status bar definition.
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)
Using video driver mali

Could not create OpenGL window:
Could not initialize OpenGL / GLES library

**Comment by madame-rachelle** [comment]
I am sure in due time that support will come. Sorry I didn't answer this sooner.

**Comment by asakous** [comment]
thank you

**Comment by dhwz** [comment]
same problem with rockchip rk3326 devices which support OpenGL ES 1.1/2.0/3.2

for my understanding this fork is the same as the added GLES support in GZDoom 4.7?

**Comment by madame-rachelle** [comment]
This repo is now redundant so it is being closed and archived. However I made the master branch match GZDoom 4.7.0.
