### ISSUE TITLE
Startup crash OpenGl ES 4.6.1

### ISSUE THREAD

**Issue by MortalWombat-repo** [drdteam/gzdoom-gles#5]
[CrashReport.zip](https://github.com/drdteam/gzdoom-gles/files/7187761/CrashReport.zip)

Running windows 10 64 bit intel gma 4500 , modded drivers. Official support ended on windows 7, and they support windows 10 nicely.

LZdoom runs, as well as older GZ legacy, but gles always a crash.

Thank you.

**Comment by madame-rachelle** [comment]
This will have to be reported on the main GZDoom repository. https://github.com/coelckers/gzdoom/issues
